//------------------------------------------------------------------------------
// Copyright (c) 2012, 2013, 2014, 2015 Francesco Paraggio.
// 
// Author: Francesco Paraggio fparaggio@gmail.com
// 
// This file is part of WindSimBattery
// 
// WindSimBattery is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
// 
// You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
// 
// The usage of a range of years within a copyright statement contained within this distribution should be interpreted as being equivalent to a list of years including the first and last year specified and all consecutive years between them. For example, a copyright statement that reads 'Copyright (c) 2005, 2007- 2009, 2011-2012' should be interpreted as being identical to a statement that reads 'Copyright (c) 2005, 2007, 2008, 2009, 2011, 2012' and a copyright statement that reads "Copyright (c) 2005-2012' should be interpreted as being identical to a statement that reads 'Copyright (c) 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012'."
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.IO;

    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.42.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "ProjectParameters.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "ProjectParameters.xsd", IsNullable = false)]





    public partial class ProjectParameters
    {

        private ProjectParametersWindSim windSimField;

        private ProjectParametersDTM dTMField;

        private ProjectParametersCFD cFDField;

        private ProjectParametersWindField windFieldField;

        /// <remarks/>
        public ProjectParametersWindSim WindSim
        {
            get
            {
                return this.windSimField;
            }
            set
            {
                this.windSimField = value;
            }
        }

        /// <remarks/>
        public ProjectParametersDTM DTM
        {
            get
            {
                return this.dTMField;
            }
            set
            {
                this.dTMField = value;
            }
        }

        /// <remarks/>
        public ProjectParametersCFD CFD
        {
            get
            {
                return this.cFDField;
            }
            set
            {
                this.cFDField = value;
            }
        }

        /// <remarks/>
        public ProjectParametersWindField WindField
        {
            get
            {
                return this.windFieldField;
            }
            set
            {
                this.windFieldField = value;
            }
        }


    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "ProjectParameters.xsd")]
    public partial class ProjectParametersWindSim
    {

        private string versionField;

        private string upgradedFromVersionField;

        private string projectTypeField;

        private object customerField;

        private string licenseHolderField;

        /// <remarks/>
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public string UpgradedFromVersion
        {
            get
            {
                return this.upgradedFromVersionField;
            }
            set
            {
                this.upgradedFromVersionField = value;
            }
        }

        /// <remarks/>
        public string ProjectType
        {
            get
            {
                return this.projectTypeField;
            }
            set
            {
                this.projectTypeField = value;
            }
        }

        /// <remarks/>
        public object Customer
        {
            get
            {
                return this.customerField;
            }
            set
            {
                this.customerField = value;
            }
        }

        /// <remarks/>
        public string LicenseHolder
        {
            get
            {
                return this.licenseHolderField;
            }
            set
            {
                this.licenseHolderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "ProjectParameters.xsd")]
    public partial class ProjectParametersDTM
    {

        private int typeField;

        private int coordSysField;

        private int xMinField;

        private int xMaxField;

        private int yMinField;

        private int yMaxField;

        private float elongationField;

        private float roughnessField;

        private bool generateCFDModelField;

        private bool generateVTFField;

        private object textureFileField;

        private bool generateGLViewFineField;

        private int smoothingTypeField;

        private float smoothingLimitField;

        private float smoothingWeightingField;

        private int forestTypeField;

        private int numberForestsField;

        private int hashCodeLastRunField;

        private ProjectParametersDTMDTMColor dTMColorField;

        private ProjectParametersDTMForestList forestListField;

        private System.DateTime lastChangedField;

        /// <remarks/>
        public int Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public int CoordSys
        {
            get
            {
                return this.coordSysField;
            }
            set
            {
                this.coordSysField = value;
            }
        }

        /// <remarks/>
        public int XMin
        {
            get
            {
                return this.xMinField;
            }
            set
            {
                this.xMinField = value;
            }
        }

        /// <remarks/>
        public int XMax
        {
            get
            {
                return this.xMaxField;
            }
            set
            {
                this.xMaxField = value;
            }
        }

        /// <remarks/>
        public int YMin
        {
            get
            {
                return this.yMinField;
            }
            set
            {
                this.yMinField = value;
            }
        }

        /// <remarks/>
        public int YMax
        {
            get
            {
                return this.yMaxField;
            }
            set
            {
                this.yMaxField = value;
            }
        }

        /// <remarks/>
        public float Elongation
        {
            get
            {
                return this.elongationField;
            }
            set
            {
                this.elongationField = value;
            }
        }

        /// <remarks/>
        public float Roughness
        {
            get
            {
                return this.roughnessField;
            }
            set
            {
                this.roughnessField = value;
            }
        }

        /// <remarks/>
        public bool GenerateCFDModel
        {
            get
            {
                return this.generateCFDModelField;
            }
            set
            {
                this.generateCFDModelField = value;
            }
        }

        /// <remarks/>
        public bool GenerateVTF
        {
            get
            {
                return this.generateVTFField;
            }
            set
            {
                this.generateVTFField = value;
            }
        }

        /// <remarks/>
        public object TextureFile
        {
            get
            {
                return this.textureFileField;
            }
            set
            {
                this.textureFileField = value;
            }
        }

        /// <remarks/>
        public bool GenerateGLViewFine
        {
            get
            {
                return this.generateGLViewFineField;
            }
            set
            {
                this.generateGLViewFineField = value;
            }
        }

        /// <remarks/>
        public int SmoothingType
        {
            get
            {
                return this.smoothingTypeField;
            }
            set
            {
                this.smoothingTypeField = value;
            }
        }

        /// <remarks/>
        public float SmoothingLimit
        {
            get
            {
                return this.smoothingLimitField;
            }
            set
            {
                this.smoothingLimitField = value;
            }
        }

        /// <remarks/>
        public float SmoothingWeighting
        {
            get
            {
                return this.smoothingWeightingField;
            }
            set
            {
                this.smoothingWeightingField = value;
            }
        }

        /// <remarks/>
        public int ForestType
        {
            get
            {
                return this.forestTypeField;
            }
            set
            {
                this.forestTypeField = value;
            }
        }

        /// <remarks/>
        public int NumberForests
        {
            get
            {
                return this.numberForestsField;
            }
            set
            {
                this.numberForestsField = value;
            }
        }

        /// <remarks/>
        public int HashCodeLastRun
        {
            get
            {
                return this.hashCodeLastRunField;
            }
            set
            {
                this.hashCodeLastRunField = value;
            }
        }

        /// <remarks/>
        public ProjectParametersDTMDTMColor DTMColor
        {
            get
            {
                return this.dTMColorField;
            }
            set
            {
                this.dTMColorField = value;
            }
        }

        /// <remarks/>
        public ProjectParametersDTMForestList ForestList
        {
            get
            {
                return this.forestListField;
            }
            set
            {
                this.forestListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime LastChanged
        {
            get
            {
                return this.lastChangedField;
            }
            set
            {
                this.lastChangedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "ProjectParameters.xsd")]
    public partial class ProjectParametersDTMDTMColor
    {

        private int rField;

        private int gField;

        private int bField;

        /// <remarks/>
        public int R
        {
            get
            {
                return this.rField;
            }
            set
            {
                this.rField = value;
            }
        }

        /// <remarks/>
        public int G
        {
            get
            {
                return this.gField;
            }
            set
            {
                this.gField = value;
            }
        }

        /// <remarks/>
        public int B
        {
            get
            {
                return this.bField;
            }
            set
            {
                this.bField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "ProjectParameters.xsd")]
    public partial class ProjectParametersDTMForestList
    {

        private float forestRoughnessField;

        private float forestHeightField;

        private float forestPorosityField;

        private float forestC1Field;

        private float forestC2Field;

        private int forestCellsZField;

        /// <remarks/>
        public float ForestRoughness
        {
            get
            {
                return this.forestRoughnessField;
            }
            set
            {
                this.forestRoughnessField = value;
            }
        }

        /// <remarks/>
        public float ForestHeight
        {
            get
            {
                return this.forestHeightField;
            }
            set
            {
                this.forestHeightField = value;
            }
        }

        /// <remarks/>
        public float ForestPorosity
        {
            get
            {
                return this.forestPorosityField;
            }
            set
            {
                this.forestPorosityField = value;
            }
        }

        /// <remarks/>
        public float ForestC1
        {
            get
            {
                return this.forestC1Field;
            }
            set
            {
                this.forestC1Field = value;
            }
        }

        /// <remarks/>
        public float ForestC2
        {
            get
            {
                return this.forestC2Field;
            }
            set
            {
                this.forestC2Field = value;
            }
        }

        /// <remarks/>
        public int ForestCellsZ
        {
            get
            {
                return this.forestCellsZField;
            }
            set
            {
                this.forestCellsZField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "ProjectParameters.xsd")]
    public partial class ProjectParametersCFD
    {

        private float borderWidthField;

        private int horizontalGridingTypeField;

        private int nodesMaxField;

        private float horizontalResolutionField;

        private float ratioAdditiveLengthToResolutionField;

        private int cellsZField;

        private float heightField;

        private string refinementFileNameField;

        private float distributionFactorField;

        private bool orthogonalizeField;

        private int refinementTypeField;

        private int simpleRefinementXMinField;

        private int simpleRefinementXMaxField;

        private int simpleRefinementYMinField;

        private int simpleRefinementYMaxField;

        private int numberSpacingsField;

        /// <remarks/>
        public float BorderWidth
        {
            get
            {
                return this.borderWidthField;
            }
            set
            {
                this.borderWidthField = value;
            }
        }

        /// <remarks/>
        public int HorizontalGridingType
        {
            get
            {
                return this.horizontalGridingTypeField;
            }
            set
            {
                this.horizontalGridingTypeField = value;
            }
        }

        /// <remarks/>
        public int NodesMax
        {
            get
            {
                return this.nodesMaxField;
            }
            set
            {
                this.nodesMaxField = value;
            }
        }

        /// <remarks/>
        public float HorizontalResolution
        {
            get
            {
                return this.horizontalResolutionField;
            }
            set
            {
                this.horizontalResolutionField = value;
            }
        }

        /// <remarks/>
        public float RatioAdditiveLengthToResolution
        {
            get
            {
                return this.ratioAdditiveLengthToResolutionField;
            }
            set
            {
                this.ratioAdditiveLengthToResolutionField = value;
            }
        }

        /// <remarks/>
        public int CellsZ
        {
            get
            {
                return this.cellsZField;
            }
            set
            {
                this.cellsZField = value;
            }
        }

        /// <remarks/>
        public float Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>
        public string RefinementFileName
        {
            get
            {
                return this.refinementFileNameField;
            }
            set
            {
                this.refinementFileNameField = value;
            }
        }

        /// <remarks/>
        public float DistributionFactor
        {
            get
            {
                return this.distributionFactorField;
            }
            set
            {
                this.distributionFactorField = value;
            }
        }

        /// <remarks/>
        public bool Orthogonalize
        {
            get
            {
                return this.orthogonalizeField;
            }
            set
            {
                this.orthogonalizeField = value;
            }
        }

        /// <remarks/>
        public int RefinementType
        {
            get
            {
                return this.refinementTypeField;
            }
            set
            {
                this.refinementTypeField = value;
            }
        }

        /// <remarks/>
        public int SimpleRefinementXMin
        {
            get
            {
                return this.simpleRefinementXMinField;
            }
            set
            {
                this.simpleRefinementXMinField = value;
            }
        }

        /// <remarks/>
        public int SimpleRefinementXMax
        {
            get
            {
                return this.simpleRefinementXMaxField;
            }
            set
            {
                this.simpleRefinementXMaxField = value;
            }
        }

        /// <remarks/>
        public int SimpleRefinementYMin
        {
            get
            {
                return this.simpleRefinementYMinField;
            }
            set
            {
                this.simpleRefinementYMinField = value;
            }
        }

        /// <remarks/>
        public int SimpleRefinementYMax
        {
            get
            {
                return this.simpleRefinementYMaxField;
            }
            set
            {
                this.simpleRefinementYMaxField = value;
            }
        }

        /// <remarks/>
        public int NumberSpacings
        {
            get
            {
                return this.numberSpacingsField;
            }
            set
            {
                this.numberSpacingsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "ProjectParameters.xsd")]
    public partial class ProjectParametersWindField
    {

        private int sectorInputTypeField;

        private object mesoProjectNameField;

        private float heightBoundaryLayerField;

        private float velocityBoundaryLayerField;

        private int boundaryConditionTopField;

        private bool useMesoInputField;

        private int doNestingField;

        private bool useInputPreviousRunField;

        private string mesoscaleDataFolderField;

        private int solverField;

        private int sweepField;

        private bool convergenceWizardField;

        private int parallelCoresField;

        private int parallelSimulationsPerCoreField;

        private float heightReducedWindDataField;

        private int hashCodeLastRunField;

        private int turbModField;

        private int monitoringSpotValueCoordSysField;

        private float monitoringSpotValueXposField;

        private float monitoringSpotValueYposField;

        private int monitoringFieldValueField;

        private bool isCoriolisField;

        private float latitudeField;

        private float temperatureField;

        private float referenceTemperatureField;

        private float temperatureGradientField;

        private float moninObukhovLengthField;

        private float referenceHeightField;

        private float windspeedInReferenceHeightField;

        private float airDensityField;

        private float radialDistributionField;

        private float kESourceField;

        private bool runInBatchModeField;

        private int[] sectorField;

        private System.DateTime lastChangedField;

        /// <remarks/>
        public int SectorInputType
        {
            get
            {
                return this.sectorInputTypeField;
            }
            set
            {
                this.sectorInputTypeField = value;
            }
        }

        /// <remarks/>
        public object MesoProjectName
        {
            get
            {
                return this.mesoProjectNameField;
            }
            set
            {
                this.mesoProjectNameField = value;
            }
        }

        /// <remarks/>
        public float HeightBoundaryLayer
        {
            get
            {
                return this.heightBoundaryLayerField;
            }
            set
            {
                this.heightBoundaryLayerField = value;
            }
        }

        /// <remarks/>
        public float VelocityBoundaryLayer
        {
            get
            {
                return this.velocityBoundaryLayerField;
            }
            set
            {
                this.velocityBoundaryLayerField = value;
            }
        }

        /// <remarks/>
        public int BoundaryConditionTop
        {
            get
            {
                return this.boundaryConditionTopField;
            }
            set
            {
                this.boundaryConditionTopField = value;
            }
        }

        /// <remarks/>
        public bool UseMesoInput
        {
            get
            {
                return this.useMesoInputField;
            }
            set
            {
                this.useMesoInputField = value;
            }
        }

        /// <remarks/>
        public int DoNesting
        {
            get
            {
                return this.doNestingField;
            }
            set
            {
                this.doNestingField = value;
            }
        }

        /// <remarks/>
        public bool UseInputPreviousRun
        {
            get
            {
                return this.useInputPreviousRunField;
            }
            set
            {
                this.useInputPreviousRunField = value;
            }
        }

        /// <remarks/>
        public string MesoscaleDataFolder
        {
            get
            {
                return this.mesoscaleDataFolderField;
            }
            set
            {
                this.mesoscaleDataFolderField = value;
            }
        }

        /// <remarks/>
        public int Solver
        {
            get
            {
                return this.solverField;
            }
            set
            {
                this.solverField = value;
            }
        }

        /// <remarks/>
        public int Sweep
        {
            get
            {
                return this.sweepField;
            }
            set
            {
                this.sweepField = value;
            }
        }

        /// <remarks/>
        public bool ConvergenceWizard
        {
            get
            {
                return this.convergenceWizardField;
            }
            set
            {
                this.convergenceWizardField = value;
            }
        }

        /// <remarks/>
        public int ParallelCores
        {
            get
            {
                return this.parallelCoresField;
            }
            set
            {
                this.parallelCoresField = value;
            }
        }

        /// <remarks/>
        public int ParallelSimulationsPerCore
        {
            get
            {
                return this.parallelSimulationsPerCoreField;
            }
            set
            {
                this.parallelSimulationsPerCoreField = value;
            }
        }

        /// <remarks/>
        public float HeightReducedWindData
        {
            get
            {
                return this.heightReducedWindDataField;
            }
            set
            {
                this.heightReducedWindDataField = value;
            }
        }

        /// <remarks/>
        public int HashCodeLastRun
        {
            get
            {
                return this.hashCodeLastRunField;
            }
            set
            {
                this.hashCodeLastRunField = value;
            }
        }

        /// <remarks/>
        public int TurbMod
        {
            get
            {
                return this.turbModField;
            }
            set
            {
                this.turbModField = value;
            }
        }

        /// <remarks/>
        public int MonitoringSpotValueCoordSys
        {
            get
            {
                return this.monitoringSpotValueCoordSysField;
            }
            set
            {
                this.monitoringSpotValueCoordSysField = value;
            }
        }

        /// <remarks/>
        public float MonitoringSpotValueXpos
        {
            get
            {
                return this.monitoringSpotValueXposField;
            }
            set
            {
                this.monitoringSpotValueXposField = value;
            }
        }

        /// <remarks/>
        public float MonitoringSpotValueYpos
        {
            get
            {
                return this.monitoringSpotValueYposField;
            }
            set
            {
                this.monitoringSpotValueYposField = value;
            }
        }

        /// <remarks/>
        public int MonitoringFieldValue
        {
            get
            {
                return this.monitoringFieldValueField;
            }
            set
            {
                this.monitoringFieldValueField = value;
            }
        }

        /// <remarks/>
        public bool IsCoriolis
        {
            get
            {
                return this.isCoriolisField;
            }
            set
            {
                this.isCoriolisField = value;
            }
        }

        /// <remarks/>
        public float Latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }

        /// <remarks/>
        public float Temperature
        {
            get
            {
                return this.temperatureField;
            }
            set
            {
                this.temperatureField = value;
            }
        }

        /// <remarks/>
        public float ReferenceTemperature
        {
            get
            {
                return this.referenceTemperatureField;
            }
            set
            {
                this.referenceTemperatureField = value;
            }
        }

        /// <remarks/>
        public float TemperatureGradient
        {
            get
            {
                return this.temperatureGradientField;
            }
            set
            {
                this.temperatureGradientField = value;
            }
        }

        /// <remarks/>
        public float MoninObukhovLength
        {
            get
            {
                return this.moninObukhovLengthField;
            }
            set
            {
                this.moninObukhovLengthField = value;
            }
        }

        /// <remarks/>
        public float ReferenceHeight
        {
            get
            {
                return this.referenceHeightField;
            }
            set
            {
                this.referenceHeightField = value;
            }
        }

        /// <remarks/>
        public float WindspeedInReferenceHeight
        {
            get
            {
                return this.windspeedInReferenceHeightField;
            }
            set
            {
                this.windspeedInReferenceHeightField = value;
            }
        }

        /// <remarks/>
        public float AirDensity
        {
            get
            {
                return this.airDensityField;
            }
            set
            {
                this.airDensityField = value;
            }
        }

        /// <remarks/>
        public float RadialDistribution
        {
            get
            {
                return this.radialDistributionField;
            }
            set
            {
                this.radialDistributionField = value;
            }
        }

        /// <remarks/>
        public float KESource
        {
            get
            {
                return this.kESourceField;
            }
            set
            {
                this.kESourceField = value;
            }
        }

        /// <remarks/>
        public bool RunInBatchMode
        {
            get
            {
                return this.runInBatchModeField;
            }
            set
            {
                this.runInBatchModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sector")]
        public int[] Sector
        {
            get
            {
                return this.sectorField;
            }
            set
            {
                this.sectorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime LastChanged
        {
            get
            {
                return this.lastChangedField;
            }
            set
            {
                this.lastChangedField = value;
            }
        }
    }

